name: ac_flutter
description: AnyCode Flutter Framework with reusable widgets, resources and extensions
version: 0.2.0
homepage: https://github.com/anycode/flutter_lib
repository: https://github.com/anycode/flutter_lib/ac_flutter
publish_to: https://pub.anycode.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  ac_dart:
    version: ^0.1.12
    hosted: https://pub.anycode.dev
  ac_ranges:
    version: ^3.0.8
    hosted: https://pub.anycode.dev
  clipboard: ^0.1.3
  cross_connectivity: ^3.3.0
  external_path: ^2.0.1
  flutter_text_viewer: ^0.0.6
  google_maps_flutter: ^2.10.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  media_storage:
    version: ^0.1.2
    hosted: https://pub.anycode.dev
  package_info_plus: ^8.1.2
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  share_plus: ^10.1.3
  shared_preferences: ^2.3.4
  version_banner:
    version: ^2.0.3
    hosted: https://pub.anycode.dev
  webview_flutter: ^4.10.0
  webview_flutter_web: ^0.2.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
#flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
