name: ac_flutter
description: AnyCode Flutter Framework with reusable widgets, resources and extensions
version: 0.1.2
homepage: https://github.com/anycode/flutter_lib
repository: https://github.com/anycode/flutter_lib/ac_flutter
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  ac_dart:
    git:
      url: https://github.com/anycode/dart_lib.git
      path: ac_dart
      ref: v0.1.2
    #path: ../../../../dart/lib/anycode/ac_dart
  ac_http_client:
    git:
      url: https://github.com/anycode/dart_lib.git
      path: ac_http_client
      ref: v0.1.2
    #path: ../../../../dart/lib/anycode/ac_http_client
  clipboard: ^0.1.3
  cross_connectivity: ^3.1.0
  flutter_text_viewer: ^0.0.6
  google_maps_flutter: ^2.5.3
  intl: ^0.19.0
  logger: ^2.0.2+1
  media_storage: ^0.0.1
  # package_info implementation with web app support
  # don't upgrade package_info_plus to 4.x to avoid packages collisions
  package_info_plus: ^5.0.1
  ranges:
    #path: ../../../../dart/lib/ranges
    git:
      url: https://github.com/anycode/ranges.dart.git
      ref: v3.0.7
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  version_banner: #^0.2.1
    git:
      url: https://github.com/anycode/flutter_version_banner
      ref: v2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

dependency_overrides:
  #http: ^1.1.2
  meta: 1.10.0
  path: 1.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
